### PR TITLE
Support TEAL 3 and 4 features

### PR DESCRIPTION
**Pull request by malturki**
This adds support for features introduced in TEAL 3 and TEAL 4.

Notes: 
1. This PR does not add any new detectors or change the way the CFG generator operates.
2. The CFG constructed now generates basic blocks of unreachable code to highlight them visually
3. The changes also address some corner cases (e.g. having a branching instruction as the last instruction in the contract)

EDIT: updated the description to include notes about supporting TEAL 4 features.

### CODE REVIEW

**Comment by montyly** [comment]
Hi @malturki, thank you for the contribution, this is great. I will review the PR asap

**Comment by ehildenb** [comment]
@montyly ping on this? We'd like to get it reviewed when convenient, and to give back a bit :)

**Comment by montyly** [comment]
Hi @ehildenb, I will review this by the end of the week, and if everything goes well, I can publish a new version on pip

**Comment by montyly** [comment]
Hi @malturki, I merged your commits with #8. This is great work, thanks again for the contribution

**Pull request merged**
